version: 2

sources:
  - name: bronze
    database: postgres
    schema: public
    tables:
      - name: E640LCT
        columns:
          - name: CODEMP
            description: Codigo da empresa
          - name: NUMLCT
            description: Numero do lancamento
          - name: TIPLCT
            description: Tipo de lancamento
          - name: ORILCT
            description: Origem do lancamento
          - name: CODFIL
            description: Codigo da filial
          - name: DATLCT
            description: Data do lancamento
          - name: CTADEB
            description: Conta de debito
          - name: CTACRE
            description: Conta de credito
          - name: VLRLCT
            description: Valor do lancamento
          - name: CODHPD
            description: CONFIRMAR DESCRICAO
          - name: CPLLCT
            description: Complemento do lancamento
          - name: NUMLOT
            description: Numero do lote
          - name: TEMRAT
            description: Tem rateio
          - name: TEMAUX
            description: Tem auxiliar
          - name: DOCLCT
            description: Documento do lancamento
          - name: CGCCPF
            description: CGC ou CPF
          - name: SITLCT
            description: Situacao do lancamento
          - name: CODUSU
            description: Codigo do usuario
          - name: DATENT
            description: Data de entrada
          - name: HORENT
            description: Hora de entrada
          - name: OBSCPL
            description: Observacao do complemento
          - name: NUMFTC
            description: CONFIRMAR DESCRICAO
          - name: CGCCRE
            description: CONFIRMAR DESCRICAO
          - name: INDLCT
            description: Indicador de lancamento
          - name: ECDLCT
            description: CONFIRMAR DESCRICAO
          - name: DATEXT
            description: CONFIRMAR DESCRICAO
          - name: IDEGED
            description: CONFIRMAR DESCRICAO
      - name: E640RAT
        columns:
          - name: CODEMP
            description: Codigo da empresa
          - name: NUMLCT
            description: Numero do lancamento
          - name: CTARED
            description: Conta de reducao
          - name: CODCCU
            description: Codigo do centro de custo
          - name: DATLCT
            description: Data do lancamento
          - name: FILRAT
            description: Filial de rateio
          - name: PERRAT
            description: Percentual de rateio
          - name: VLRRAT
            description: Valor do rateio
          - name: SITRAT
            description: Situacao do rateio
          - name: DEBCRE
            description: Divida ou credito
          - name: CTAFIN
            description: Conta financeiro
          - name: NUMFTC
            description: Numero da fatura
      - name: E600MCC
        columns:
          - name: CODEMP
            description: Codigo da empresa
          - name: NUMCCO
            description: Numero da conta corrente
          - name: DATMOV
            description: Data da movimentacao
          - name: SEQMOV
            description: Sequencia da movimentacao
          - name: CODTNS
            description: Codigo da transacao
          - name: ORIMCC
            description: Origem da movimentacao
          - name: TIPMCC
            description: Tipo da movimentacao
          - name: CODNTG
            description: Codigo da natureza da movimentacao
          - name: DATCTB
            description: Data da contabilizacao
          - name: CODDOC
            description: Codigo do documento
          - name: DOCMOV
            description: Documento da movimentacao
          - name: NUMPRJ
            description: Numero do projeto
          - name: CODFPJ
            description: Codigo do projeto
          - name: CTAFIN
            description: Conta de financiamento
          - name: CTARED
            description: Conta de reembolso
          - name: CODCCU
            description: Codigo do centro de custo
          - name: HISMOV
            description: Historico da movimentacao
          - name: NROCHE
            description: Numero do cheque
          - name: VLRMOV
            description: Valor da movimentacao
          - name: DEBCRE
            description: Divida ou credito
          - name: NOMREC
            description: Nome do recebedor
          - name: CPLMOV
            description: Complemento da movimentacao
          - name: DATLIB
            description: Data da liberacao
          - name: VLRPIS
            description: Valor do PIS
          - name: VLRBPR
            description: Valor do BPR
          - name: VLRCOF
            description: Valor do cofins
          - name: VLRBCR
            description: Valor do BCR
          - name: ORICON
            description: Origem da conta
          - name: DATCON
            description: Data da conta
          - name: SEQCON
            description: Sequencia da conta
          - name: CODFIL
            description: Codigo do filial
          - name: TIPCNC
            description: Tipo de conta
          - name: USUCNC
            description: Usuario da conta
          - name: DATCNC
            description: Data da conta
          - name: HORCNC
            description: Hora da conta
      - name: E640LOT
      - name: E046HPD
      - name: E044CCU
      - name: E045PLA
      - name: E070FIL
      - name: E070EMP
      
