WITH DATE_RANGES AS (
    SELECT
        MIN("DATLCT") AS start_date,
        MAX("DATLCT") AS end_date
    FROM {{ ref('lancamentos') }}
),
DATE_SERIES AS (
    SELECT
        generate_series(
            (SELECT start_date FROM DATE_RANGES),
            (SELECT end_date FROM DATE_RANGES) + INTERVAL '1 day' - INTERVAL '1 day',
            '1 day'::interval
        ) AS "DATA"
    FROM DATE_RANGES
)

SELECT DISTINCT
    CAST("DATA" AS DATE) AS "DATA",
    DATE_TRUNC('month', "DATA")::DATE AS "PRIMEIRO_DIA_DO_MES",
    (DATE_TRUNC('month', "DATA") + INTERVAL '1 month' - INTERVAL '1 day')::DATE AS "ULTIMO_DIA_DO_MES",
    EXTRACT(YEAR FROM "DATA") AS "ANO",
    CEIL(EXTRACT(MONTH FROM "DATA") / 6.0) AS "SEMESTRE",
    EXTRACT(QUARTER FROM "DATA") AS "TRIMESTRE",
    EXTRACT(QUARTER FROM "DATA") || 'T' || TO_CHAR("DATA", 'YY') AS "TRIMESTRE_ANO",
    EXTRACT(MONTH FROM "DATA") AS "MES",
    CASE 
        WHEN EXTRACT(MONTH FROM "DATA") = 1 THEN 'JAN'
        WHEN EXTRACT(MONTH FROM "DATA") = 2 THEN 'FEV'
        WHEN EXTRACT(MONTH FROM "DATA") = 3 THEN 'MAR'
        WHEN EXTRACT(MONTH FROM "DATA") = 4 THEN 'ABR'
        WHEN EXTRACT(MONTH FROM "DATA") = 5 THEN 'MAI'
        WHEN EXTRACT(MONTH FROM "DATA") = 6 THEN 'JUN'
        WHEN EXTRACT(MONTH FROM "DATA") = 7 THEN 'JUL'
        WHEN EXTRACT(MONTH FROM "DATA") = 8 THEN 'AGO'
        WHEN EXTRACT(MONTH FROM "DATA") = 9 THEN 'SET'
        WHEN EXTRACT(MONTH FROM "DATA") = 10 THEN 'OUT'
        WHEN EXTRACT(MONTH FROM "DATA") = 11 THEN 'NOV'
        WHEN EXTRACT(MONTH FROM "DATA") = 12 THEN 'DEZ'
    END || '-' || TO_CHAR("DATA", 'YY') AS "MES_ANO",
    CASE 
        WHEN EXTRACT(MONTH FROM "DATA") = 1 THEN 'JANEIRO'
        WHEN EXTRACT(MONTH FROM "DATA") = 2 THEN 'FEVEREIRO'
        WHEN EXTRACT(MONTH FROM "DATA") = 3 THEN 'MARCO'
        WHEN EXTRACT(MONTH FROM "DATA") = 4 THEN 'ABRIL'
        WHEN EXTRACT(MONTH FROM "DATA") = 5 THEN 'MAIO'
        WHEN EXTRACT(MONTH FROM "DATA") = 6 THEN 'JUNHO'
        WHEN EXTRACT(MONTH FROM "DATA") = 7 THEN 'JULHO'
        WHEN EXTRACT(MONTH FROM "DATA") = 8 THEN 'AGOSTO'
        WHEN EXTRACT(MONTH FROM "DATA") = 9 THEN 'SETEMBRO'
        WHEN EXTRACT(MONTH FROM "DATA") = 10 THEN 'OUTUBRO'
        WHEN EXTRACT(MONTH FROM "DATA") = 11 THEN 'NOVEMBRO'
        WHEN EXTRACT(MONTH FROM "DATA") = 12 THEN 'DEZEMBRO'
    END AS "MES_DESCRICAO",
    EXTRACT(WEEK FROM "DATA") AS "SEMANA",
    FLOOR((EXTRACT(DAY FROM "DATA") - 1) / 7) + 1 AS "SEMANA_DO_MES",
    EXTRACT(DAY FROM "DATA") AS "DIA",
    EXTRACT(DOY FROM "DATA") AS "DIA_DO_ANO",
    EXTRACT(DOW FROM "DATA") AS "DIA_DA_SEMANA",
    CASE
        WHEN EXTRACT(DOW FROM "DATA") = 0 THEN 'DOMINGO'
        WHEN EXTRACT(DOW FROM "DATA") = 1 THEN 'SEGUNDA'
        WHEN EXTRACT(DOW FROM "DATA") = 2 THEN 'TERCA'
        WHEN EXTRACT(DOW FROM "DATA") = 3 THEN 'QUARTA'
        WHEN EXTRACT(DOW FROM "DATA") = 4 THEN 'QUINTA'
        WHEN EXTRACT(DOW FROM "DATA") = 5 THEN 'SEXTA'
        WHEN EXTRACT(DOW FROM "DATA") = 6 THEN 'SABADO'
    END AS "DIA_DA_SEMANA_DESCRICAO"
FROM DATE_SERIES
