WITH FATO_LANCAMENTOS AS (
    SELECT DISTINCT
        "SK_LCT",
        "SK_CCU",
        "SK_CTA",
        "SK_RAT",
        "SK_FIL",
        "SK_LOT",
        -- "CODEMP",
        -- "CODFIL",
        -- "FILRAT",
        -- "NUMLCT",
        "DATLCT",
        -- "CODCCU",
        "CODHPD",
        -- "NUMLOT",
        -- "TEMRAT",
        -- "TEMAUX",
        -- "DOCLCT",
        -- "CGCCPF",
        -- "CGCCRE",
        -- "CODUSU",
        -- "NUMFTC",
        -- "DATENT",
        -- "HORENT",
        "PERRAT",
        "VLRRAT"--,
        -- "SMEFIL"
        -- "TIPLCT",
        -- "ORILCT",
        -- "CPLLCT",
        -- "SITLCT",
        -- "OBSCPL",
        -- "INDLCT",
        -- "ECDLCT",
        -- "CTADEB",
        -- "CTACRE",
        -- "VLRLCT",
        -- "DATEXT",
        -- "IDEGED",
        -- "CTARED",
        -- "SITRAT",
        -- "DEBCRE",
        -- "CTAFIN",
    FROM {{ ref('lancamentos') }}
)

SELECT * FROM FATO_LANCAMENTOS